version: '3.7'

networks:
  database:
    external: false

services:

  devapp:
    image: alexa-parkinson
    build: .
    ports:
        - '12118:12118'
    volumes:
        - './:/usr/dockers/devapp/'
    entrypoint: Docker/docker-entrypoint.sh
    restart: always
    networks:
      - database

  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER="parkinson_user"
      - MONGODB_PASS="jkvhskjbvserj45oiheowr"
    ports:
      - '27017:27017'
    restart: always
    networks:
      - database
