version: '3.7'

networks:
  database:
    external: false

services:

  devapp:
    image: alexa-parkinson
    build: .
    depends_on:
      - db
      #db:
      #  condition: service_healthy
    ports:
        - '12118:12118'
    volumes:
        - './:/usr/dockers/devapp/'
    entrypoint: Docker/docker-entrypoint.sh
    restart: always
    networks:
      - database

  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER="parkinson_user"
      - MONGODB_PASS="jkvhskjbvserj45oiheowr"
    volumes:
      - ./data/db:/data/db
    # env_file:
    #   - env/mongo.env
    entrypoint: mongod --auth
    restart: always
    networks:
      - database
