version: '2'
services:

  devapp:
    image: alexa-parkinson
    build: .
    ports:
        - '12114:12114'
    volumes:
        - './:/usr/dockers/devapp/'
    entrypoint: Docker/docker-entrypoint.sh
    restart: always